### ISSUE TITLE
Rough Mobs and you!

### ISSUE THREAD

**Issue by bookerthegeek** [Funwayguy/Epic-Siege-Mod#66]
## Heyo ##
Tis seemly that thou mod and one of thy other favorite mob modifying mod are at odds in regards to something. Thought I would let you know so everybody could place nice together?
### What Happened ###
```
java.lang.ClassCastException: net.minecraft.entity.monster.EntityWitherSkeleton cannot be cast to net.minecraft.entity.monster.EntitySkeleton
	at lellson.roughMobs.events.SkeletonEvents.onWorldJoin(SkeletonEvents.java:104)
	at lellson.roughMobs.events.SkeletonEvents.onWorldJoin(SkeletonEvents.java:35)
	at lellson.roughMobs.events.DefaultEvents.eventJoinWorld(DefaultEvents.java:87)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_652_DefaultEvents_eventJoinWorld_EntityJoinWorldEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraft.world.World.func_72838_d(World.java:1198)
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1066)
	at funwayguy.epicsiegemod.handlers.entities.SkeletonHandler.onEntitySpawn(SkeletonHandler.java:69)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_397_SkeletonHandler_onEntitySpawn_EntityJoinWorldEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraft.world.World.func_72838_d(World.java:1198)
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1066)
	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:160)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:197)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Unknown Source)
```
### What did I expect to Happen? ###
For the game to be playable beyond the first skeleton spawning into the world.

### Versions ###
- Minecraft 1.11.x
- Forge: 13.20.0.2296
- Rough Mobs: 1.0.9-1.11.2
- Epic Siege Mod: 12.0.157

#### Additional Information ####
The silly rabbit does not have a github to report issues, I could only find an issue tracker on the [CurseForge](https://minecraft.curseforge.com/projects/rough-mobs/issues) page. I will be creating an Issue their linking to here.

**Comment by Morpheus1101** [comment]
This looks like more an issue with roughmobs than ESM, but since its only a snippet of the crash log cant be certain

**Comment by bookerthegeek** [comment]
Gotcha. Did not realize more was needed. I'll post it when i get home.

Found how to reproduce though, spawn skeletons in the overworld. Wither skeletons.

**Comment by bookerthegeek** [comment]
Sorry it took so long to respond, here is a [crash report][1] with updated mobs. No config changes.

[1]:https://gist.github.com/bookerthegeek/9489ff730b9eab28dfaf5c50584be5c8
