### ISSUE TITLE
Game crashes whenever zombies remove torches?

### ISSUE THREAD

**Issue by DogeKnight** [Funwayguy/Epic-Siege-Mod#9]
So yeah, the mod seems to work alright, except when the zombies do this "torch.break" function, which causes the game to crash. Heres the error report I get almost every time...
---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 2/28/15 9:41 AM
Description: Ticking entity

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at funwayguy.esm.ai.ESM_EntityAITorchBreak.func_75250_a(ESM_EntityAITorchBreak.java:64)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:70)
	at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:540)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1772)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(SourceFile:25)
	at net.minecraft.entity.monster.EntityZombie.func_70636_d(EntityZombie.java:217)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1609)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:30)
	at net.minecraft.entity.monster.EntityZombie.func_70071_h_(EntityZombie.java:303)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
	Entity Type: Zombie (net.minecraft.entity.monster.EntityZombie)
	Entity ID: 408956
	Entity Name: Zombie
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_31, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 185845184 bytes (177 MB) / 554553344 bytes (528 MB) up to 1060372480 bytes (1011 MB)

Yeah so anyway. Whenever I enter a world, if there's a mineshaft nearby I'm guessing, and a zombie is down there, it instantly crashes. Its very frustrating. I'm running other mods, but I've already tested compatibility and it's not the mods, it's this torch break thing. So anyway, do I need some sort of plugin or mod to make this one work? Or is just a common error?

**Comment by Funwayguy** [comment]
I'll get this fixed up soon. I just bricked my OS recently so it might take a while to get my dev environment back in working order to work on this. I assume this is on the latest version too?

**Comment by Funwayguy** [comment]
There seems to be some vital information missing from the log, are you sure this is the FULL crash log?

**Comment by DogeKnight** [comment]
Yes it was on the latest version, no I left out some stuff from the log because I thought it was not relevant (But I'm most likely mistaken) Here is the entire crash report if you still need it.

---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 2/28/15 9:41 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at funwayguy.esm.ai.ESM_EntityAITorchBreak.func_75250_a(ESM_EntityAITorchBreak.java:64)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:70)
	at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:540)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1772)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(SourceFile:25)
	at net.minecraft.entity.monster.EntityZombie.func_70636_d(EntityZombie.java:217)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1609)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:30)
	at net.minecraft.entity.monster.EntityZombie.func_70071_h_(EntityZombie.java:303)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at funwayguy.esm.ai.ESM_EntityAITorchBreak.func_75250_a(ESM_EntityAITorchBreak.java:64)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:70)
	at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:540)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1772)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(SourceFile:25)
	at net.minecraft.entity.monster.EntityZombie.func_70636_d(EntityZombie.java:217)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1609)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:30)
	at net.minecraft.entity.monster.EntityZombie.func_70071_h_(EntityZombie.java:303)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
	Entity Type: Zombie (net.minecraft.entity.monster.EntityZombie)
	Entity ID: 408956
	Entity Name: Zombie
	Entity's Exact location: -328.22, 5.00, 288.64
	Entity's Block location: World: (-329,5,288), Chunk: (at 7,0,0 in -21,18; contains blocks -336,0,288 to -321,255,303), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: -0.04, -0.08, -0.03
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['Razorkill333'/1914, l='New World', x=-325.30, y=5.00, z=291.41]]
	Chunk stats: ServerChunkCache: 600 Drop: 0
	Level seed: 940237346379303687
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-300,4,407), Chunk: (at 4,0,7 in -19,25; contains blocks -304,0,400 to -289,255,415), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1733 game time, 1733 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 96678 (now: false), thunder time: 122519 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_31, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 185845184 bytes (177 MB) / 554553344 bytes (528 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1236 Minecraft Forge 10.13.2.1236 20 mods loaded, 20 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1236} [Forge Mod Loader] (forge-1.7.10-10.13.2.1236.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1236} [Minecraft Forge] (forge-1.7.10-10.13.2.1236.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TooManyItems{1.7.10} [TooManyItems] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildMod{v1.0} [Build Mod] (CoroUtil-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CoroAI{v1.0} [CoroAI] (CoroUtil-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ExtendedRenderer{v1.0} [Extended Renderer] (CoroUtil-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ConfigMod{v1.0} [Extended Mod Config] (CoroUtil-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CustomSpawner{3.3.0} [DrZhark's CustomSpawner] (CustomMobSpawner 3.3.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ESM{10.0.92} [Epic Siege Mod] (EpicSiegeMod-10.0.92.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	flansmod{4.9.0} [Flan's Mod] (Flans Mod-1.7.10-4.9.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	radixcore{1.3.3} [RadixCore] (RadixCore-1.7.x-1.3.3-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	mca{4.1.4} [Minecraft Comes Alive] (MCA-1.7.10-4.1.4-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	mcheli{0.10.2} [MC Helicopter] (mcheli) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	movillages{1.2.1} [Mo' Villages] (MoVillages-1.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	rancraftpenguins{1.7.10q} [Rancraft Penguins] (rancraftpenguins-1.7.10q.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TwilightForest{2.3.2} [The Twilight Forest] (twilightforest-1.7.10-2.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	weaponmod{1.7.2 v1.14.2} [Balkon's WeaponMod] (weaponmod-1.14.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	weather2{v2.3.4} [weather2] (Weather-2.3.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['Razorkill333'/1914, l='New World', x=-325.30, y=5.00, z=291.41]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

Thanks for responding, I appreciate that you actively fix bugs, that's pretty awesome.
